// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXWYL3rItwljCw40fqS9sWj5YgWs-KtQ',
    appId: '1:692671428334:web:b1934e13e64c1c7dbb65ff',
    messagingSenderId: '692671428334',
    projectId: 'af-05-07-24',
    authDomain: 'af-05-07-24.firebaseapp.com',
    storageBucket: 'af-05-07-24.appspot.com',
    measurementId: 'G-4KHQ0WDRZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYdsJyxvpsXRvWrVWZPZiuOeUAvyztUyE',
    appId: '1:692671428334:android:86c9f7478a8f521bbb65ff',
    messagingSenderId: '692671428334',
    projectId: 'af-05-07-24',
    storageBucket: 'af-05-07-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUKJ3WCkCpSGvR61J-ZErfJA-Ra_o6RsU',
    appId: '1:692671428334:ios:68f1f56824f1c3e5bb65ff',
    messagingSenderId: '692671428334',
    projectId: 'af-05-07-24',
    storageBucket: 'af-05-07-24.appspot.com',
    iosBundleId: 'com.example.revFbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUKJ3WCkCpSGvR61J-ZErfJA-Ra_o6RsU',
    appId: '1:692671428334:ios:68f1f56824f1c3e5bb65ff',
    messagingSenderId: '692671428334',
    projectId: 'af-05-07-24',
    storageBucket: 'af-05-07-24.appspot.com',
    iosBundleId: 'com.example.revFbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJXWYL3rItwljCw40fqS9sWj5YgWs-KtQ',
    appId: '1:692671428334:web:db235f9c74d9de43bb65ff',
    messagingSenderId: '692671428334',
    projectId: 'af-05-07-24',
    authDomain: 'af-05-07-24.firebaseapp.com',
    storageBucket: 'af-05-07-24.appspot.com',
    measurementId: 'G-4SG2GJXLTE',
  );
}
